### PR TITLE
Add Skin API and Backwards Compatibilty

### PR DESCRIPTION
**Pull request by Techcable**
- Allows Developers to change the skin the player will see
- Re adds support for 1.7.10
- Adds support for Protocol Hack

### CODE REVIEW

**Comment by Techcable** [comment]
Just a second let me fix the merge conflicts.

**Comment by Techcable** [comment]
There, I fixed the merge conflicts.

**Comment by Techcable** [comment]
@md-5 
Could you please comment on this PR.

**Comment by md-5** [comment]
Yes, iTag is meant to be a simple drop in replacement for TagAPI.

This adds a _tonne_ of code, basically tripling its size. Why is it needed?

**Comment by Techcable** [comment]
Many developers wouldn't like players to see the original skin, and some would.
If i'm implementing a disguise plugin, and set a player's name to their new disguise players would still see their old skin.
If i'm implementing a nick name plugin, i wan't players to retain their original skin.
This gives developers full control over what skin a player sees.
In fact in the 1.8 implementation (and maybe 1.7.10) properties aren't copied so skins won't be shown.
This plugin fixes, that issue and gives developers full control over skins.

**Comment by ams2990** [comment]
This solves one problem, but creates another. With the currently released version of iTag, skins are not sent to clients, ever. This PR fixes that problem, but a plugin I wrote to change player names no longer works as the name changes never actually happen.

**Comment by Techcable** [comment]
@ams2990 
Could you please show your code?

**Comment by ams2990** [comment]
It's part of a larger plugin, but the relevant section is here:

```
@EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
public void onNameTag(AsyncPlayerReceiveNameTagEvent event) {
    event.setTag(infoManager.getDisplayName(event.getNamedPlayer()));
}
```

where `infoManager.getDisplayName(event.getNamedPlayer())` just looks up the name it should be sending.

**Comment by Techcable** [comment]
Maybe the changes i made to the version detection broke it. Was it working before?

**Comment by ams2990** [comment]
Yes. It worked on 1.1.0-SNAPSHOT (the currently released version). It stopped working when I updated to 1.2.0 (built from your PR).

**Comment by ams2990** [comment]
Any progress on fixing this?

**Comment by Techcable** [comment]
@ams2990 
Could you give me the source of your nametag plugin?

**Comment by ams2990** [comment]
I created a minimal example for you at [ams2990/NametagTesting](https://github.com/ams2990/NametagTesting). It tags each player with a random 15 or 16 character string.

On 1.7 and TagAPI, the player is correctly given a random nametag.
On 1.8 and iTag at HEAD, the player is correctly given a random nametag.
On 1.8 and iTag with this PR, this player's nametag is NOT altered.

**Comment by Techcable** [comment]
@ams2990
It works for me on 1.8.3.
It works

**Comment by ams2990** [comment]
**That's** interesting. You get the same result with and without your PR?

**Comment by Techcable** [comment]
@ams2990 
I haven't tried without my PR.
Are you on offline mode by any chance?

**Comment by ams2990** [comment]
I don't believe so. I'm not in front of my computer right now so I can't check. I'll tell you tonight.

**Comment by ams2990** [comment]
Ah, I see why:

```
[20:27:44 ERROR]: [iTag] Unsupported Version
[20:27:44 ERROR]: [iTag] Shutting Down
```

Are you running 1.8.3?

**Comment by Techcable** [comment]
@ams2990 
I am running 1.8.3. Do you have the correct version of protocol lib?
@md-5 
Bump

**Comment by ams2990** [comment]
You tell me:

```
>version ProtocolLib
[22:20:41 INFO]: ProtocolLib version 3.6.3-SNAPSHOT-b114

>version
[22:21:10 INFO]: This server is running CraftBukkit version git-Spigot-2f787bd-1a1bc08 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
```

**Comment by Techcable** [comment]
@ams2990 
Looks like you are a few protocol lib versions behind.
Try to update [here](http://ci.shadowvolt.com/job/ProtocolLib/).

**Comment by ams2990** [comment]
Oh ho! It was ProtocolLib all along! I apologize for incorrectly blaming your code.

My only nit to pick now is the skin doesn't change with the player name. With TagAPI, when you changed the player's name, the skin changed too. For compatibility reasons, if the skin isn't explicitly set in the event, you should set it to the skin matching the new name.

**Comment by Techcable** [comment]
@ams2990 
So if skin isn't explicitly set strip the tag's color codes and change skin?

**Comment by ams2990** [comment]
Yes.

**Comment by ams2990** [comment]
Doesn't this override it even if the skin was previously set?

**Comment by ams2990** [comment]
LGTM. Fixes the skin bug in the existing code, maintains compatibility, and adds a nice new feature that I will _definitely_ be taking advantage of.

**Comment by Techcable** [comment]
@md-5 
I'm going to rebase this. Then can you pull?

**Comment by Techcable** [comment]
bump

**Comment by md-5** [comment]
Again, you should do this in parts.

at this point in time I only care about fixing rather than all these new features and tonnes of extra code.

**Comment by Techcable** [comment]
@md-5 
I'll just be forking iTag.
I think we have different goals in mind for the plugin.

**Pull request closed without merging**
